/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kuisgame;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rosyid Iz
 */
public class FrameWelcome extends javax.swing.JFrame {
    
    DefaultTableModel scoreModel;
    

    /**
     * Creates new form FrameWelcome
     */
    public FrameWelcome() {
        initComponents();
        scoreModel = (DefaultTableModel) tableScore.getModel();
        tableScore.setModel(scoreModel);
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLeftWelcome = new javax.swing.JPanel();
        labelTitleApp = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        buttonMulai = new javax.swing.JButton();
        panelRightWelcome = new javax.swing.JPanel();
        closePanel = new javax.swing.JPanel();
        X = new javax.swing.JLabel();
        labelTopScore = new javax.swing.JLabel();
        panelScore = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableScore = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kuis Game");
        setFocusCycleRoot(false);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setName("frameWelcome"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLeftWelcome.setBackground(new java.awt.Color(111, 90, 126));
        panelLeftWelcome.setFocusable(false);
        panelLeftWelcome.setRequestFocusEnabled(false);
        panelLeftWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitleApp.setFont(new java.awt.Font("THE CHAMP", 0, 102)); // NOI18N
        labelTitleApp.setForeground(new java.awt.Color(255, 174, 143));
        labelTitleApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitleApp.setText("<html> <center>KUIS<br/> GAME</center> </html");
        panelLeftWelcome.add(labelTitleApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 310));

        inputNama.setFont(new java.awt.Font("THE CHAMP", 0, 22)); // NOI18N
        inputNama.setForeground(new java.awt.Color(255, 103, 125));
        inputNama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputNama.setText("MASUKKAN NAMA");
        inputNama.setAutoscrolls(false);
        inputNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 103, 125)));
        inputNama.setCaretColor(new java.awt.Color(255, 174, 143));
        inputNama.setFocusCycleRoot(true);
        inputNama.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                inputNamaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        panelLeftWelcome.add(inputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 240, 50));

        buttonMulai.setBackground(new java.awt.Color(255, 103, 125));
        buttonMulai.setFont(new java.awt.Font("THE CHAMP", 0, 22)); // NOI18N
        buttonMulai.setForeground(new java.awt.Color(255, 255, 255));
        buttonMulai.setText("MULAI");
        buttonMulai.setBorder(null);
        buttonMulai.setBorderPainted(false);
        buttonMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMulaiActionPerformed(evt);
            }
        });
        panelLeftWelcome.add(buttonMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 240, 50));

        getContentPane().add(panelLeftWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 500));

        panelRightWelcome.setBackground(new java.awt.Color(252, 246, 246));
        panelRightWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closePanel.setBackground(new java.awt.Color(205, 102, 132));
        closePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closePanelMouseClicked(evt);
            }
        });

        X.setFont(new java.awt.Font("THE CHAMP", 0, 24)); // NOI18N
        X.setForeground(new java.awt.Color(255, 255, 255));
        X.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        X.setText("X");
        closePanel.add(X);

        panelRightWelcome.add(closePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 30, 30));

        labelTopScore.setFont(new java.awt.Font("THE CHAMP", 0, 34)); // NOI18N
        labelTopScore.setForeground(new java.awt.Color(255, 103, 125));
        labelTopScore.setText("TOP SCORE");
        panelRightWelcome.add(labelTopScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        panelScore.setBackground(new java.awt.Color(51, 51, 51));
        panelScore.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelScore.setOpaque(false);
        panelScore.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("THE CHAMP", 0, 12)); // NOI18N

        tableScore.setBackground(new java.awt.Color(51, 51, 51));
        tableScore.setFont(new java.awt.Font("THE CHAMP", 0, 12)); // NOI18N
        tableScore.setForeground(new java.awt.Color(255, 103, 125));
        tableScore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "NAMA", "SCORE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableScore.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tableScore.setAutoscrolls(false);
        tableScore.setGridColor(new java.awt.Color(255, 103, 125));
        tableScore.setIntercellSpacing(new java.awt.Dimension(2, 2));
        tableScore.getTableHeader().setResizingAllowed(false);
        tableScore.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableScore);

        panelScore.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 390));

        panelRightWelcome.add(panelScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 300, 390));

        getContentPane().add(panelRightWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 340, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closePanelMouseClicked
        this.dispose();
    }//GEN-LAST:event_closePanelMouseClicked

    private void buttonMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMulaiActionPerformed
        this.setVisible(false);
        new FrameMulaiKuis().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonMulaiActionPerformed

    private void inputNamaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_inputNamaAncestorAdded
        inputNama.setBounds(50,100,100,50);
    }//GEN-LAST:event_inputNamaAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameWelcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel X;
    private javax.swing.JButton buttonMulai;
    private javax.swing.JPanel closePanel;
    private javax.swing.JTextField inputNama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitleApp;
    private javax.swing.JLabel labelTopScore;
    private javax.swing.JPanel panelLeftWelcome;
    private javax.swing.JPanel panelRightWelcome;
    private javax.swing.JPanel panelScore;
    private javax.swing.JTable tableScore;
    // End of variables declaration//GEN-END:variables

    private void LoadData() {
//        try {
//            Connection con = ConnectDB.getKoneksi();
//            Statement s = con.createStatement();
//            String query = "SELECT * FROM score";
//        } catch (SQLException e) {
//            System.out.println("Error: LoadData()");
//        }
    }
}
