package kuisgame;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.BooleanControl;
import javax.sound.sampled.Mixer;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Rosyid Iz
 */
public class FrameWelcome extends javax.swing.JFrame {
    
    Connection conn;
    Statement s;
    DefaultTableModel scoreModel;
    CustomHeaderScore customHeader = new CustomHeaderScore();

    /**
     * Creates new form FrameWelcome
     */
    public FrameWelcome() {
        initComponents();
        conn = ConnectDB.getKoneksi(); // koneksi database
        new EnableDrag(this); // halaman bisa di drag
        scoreModel = (DefaultTableModel) tableScore.getModel(); //membuat table
        tableScore.setModel(scoreModel);
        TableColumnModel tbl = tableScore.getColumnModel();
        tbl.getColumn(0).setPreferredWidth(30); // mengatur ukuran kolom
        tbl.getColumn(1).setPreferredWidth(190);
        tbl.getColumn(2).setPreferredWidth(80);
        DefaultTableCellRenderer centerTxt = new DefaultTableCellRenderer();
        centerTxt.setHorizontalAlignment(JLabel.CENTER); // setting rata tengah
        tableScore.getColumnModel().getColumn(0).setCellRenderer(centerTxt); // kolom 0 rata tengah
        tableScore.getColumnModel().getColumn(2).setCellRenderer(centerTxt);
        tableScore.getTableHeader().setBackground(Color.BLACK); // set kolom background header
        tableScore.getTableHeader().setDefaultRenderer(customHeader); // menerapkan setting headaer
        LoadData(); // menampilkan data dari database
    }
    
    private void setNama(String nama) {
        try {
            s = conn.createStatement();
            // Membuat Query SELECT
            String sql = "INSERT INTO user VALUES (null,?,0)";
//            s.executeQuery(sql);
            PreparedStatement p = conn.prepareStatement(sql);
            p.setString(1, nama);
            p.executeUpdate();
            p.close();
            
        } catch(SQLException e) {
            System.out.println("Error: Nama tidak tersimpan!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase = new javax.swing.JPanel();
        panelLeftWelcome = new javax.swing.JPanel();
        iconLoginAdmin = new javax.swing.JLabel();
        labelTitleApp = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        buttonMulai = new javax.swing.JButton();
        panelRightWelcome = new javax.swing.JPanel();
        labelTopScore = new javax.swing.JLabel();
        panelScore = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableScore = new javax.swing.JTable();
        panelCustomBar = new javax.swing.JPanel();
        buttonMinimized = new javax.swing.JLabel();
        buttonClose = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kuis Game");
        setBackground(new java.awt.Color(25, 9, 52));
        setFocusCycleRoot(false);
        setForeground(new java.awt.Color(240, 240, 240));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setName("frameWelcome"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBase.setBackground(new java.awt.Color(255, 255, 255));
        panelBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBaseMouseClicked(evt);
            }
        });
        panelBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLeftWelcome.setBackground(new java.awt.Color(111, 90, 126));
        panelLeftWelcome.setFocusable(false);
        panelLeftWelcome.setMaximumSize(new java.awt.Dimension(460, 430));
        panelLeftWelcome.setRequestFocusEnabled(false);
        panelLeftWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconLoginAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLoginAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kuisgame/user-3-very-small.png"))); // NOI18N
        iconLoginAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconLoginAdminMouseClicked(evt);
            }
        });
        panelLeftWelcome.add(iconLoginAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        labelTitleApp.setFont(new java.awt.Font("THE CHAMP", 0, 102)); // NOI18N
        labelTitleApp.setForeground(new java.awt.Color(255, 174, 143));
        labelTitleApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitleApp.setText("<html> <center>KUIS<br/> GAME</center> </html");
        panelLeftWelcome.add(labelTitleApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 310));

        inputNama.setFont(new java.awt.Font("THE CHAMP", 0, 22)); // NOI18N
        inputNama.setForeground(new java.awt.Color(255, 103, 125));
        inputNama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputNama.setText("MASUKKAN NAMA");
        inputNama.setAutoscrolls(false);
        inputNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 103, 125)));
        inputNama.setCaretColor(new java.awt.Color(255, 174, 143));
        inputNama.setFocusCycleRoot(true);
        panelLeftWelcome.add(inputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 240, 50));

        buttonMulai.setBackground(new java.awt.Color(255, 103, 125));
        buttonMulai.setFont(new java.awt.Font("THE CHAMP", 0, 22)); // NOI18N
        buttonMulai.setForeground(new java.awt.Color(255, 255, 255));
        buttonMulai.setText("MULAI");
        buttonMulai.setBorder(null);
        buttonMulai.setBorderPainted(false);
        buttonMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMulaiActionPerformed(evt);
            }
        });
        panelLeftWelcome.add(buttonMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 240, 50));

        panelBase.add(panelLeftWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 500));

        panelRightWelcome.setBackground(new java.awt.Color(252, 246, 246));
        panelRightWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTopScore.setFont(new java.awt.Font("THE CHAMP", 0, 34)); // NOI18N
        labelTopScore.setForeground(new java.awt.Color(255, 103, 125));
        labelTopScore.setText("TOP SCORE");
        panelRightWelcome.add(labelTopScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        panelScore.setBackground(new java.awt.Color(51, 51, 51));
        panelScore.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelScore.setOpaque(false);
        panelScore.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("THE CHAMP", 0, 12)); // NOI18N

        tableScore.setBackground(new java.awt.Color(51, 51, 51));
        tableScore.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tableScore.setForeground(new java.awt.Color(255, 103, 125));
        tableScore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "NAMA", "SCORE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableScore.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableScore.setAutoscrolls(false);
        tableScore.setGridColor(new java.awt.Color(255, 103, 125));
        tableScore.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableScore.setRowHeight(35);
        tableScore.setRowSelectionAllowed(false);
        tableScore.getTableHeader().setReorderingAllowed(false);
        tableScore.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(tableScore);

        panelScore.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 390));

        panelRightWelcome.add(panelScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 300, 390));

        panelBase.add(panelRightWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 340, 500));

        getContentPane().add(panelBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 820, 520));

        panelCustomBar.setBackground(new java.awt.Color(51, 51, 51));
        panelCustomBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonMinimized.setFont(new java.awt.Font("THE CHAMP", 0, 30)); // NOI18N
        buttonMinimized.setForeground(new java.awt.Color(255, 255, 255));
        buttonMinimized.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonMinimized.setText("_");
        buttonMinimized.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMinimizedMouseClicked(evt);
            }
        });
        panelCustomBar.add(buttonMinimized, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 40, 40));

        buttonClose.setFont(new java.awt.Font("THE CHAMP", 0, 30)); // NOI18N
        buttonClose.setForeground(new java.awt.Color(255, 255, 255));
        buttonClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonClose.setText("X");
        buttonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCloseMouseClicked(evt);
            }
        });
        panelCustomBar.add(buttonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 40, 40));

        jToggleButton1.setBackground(new java.awt.Color(0, 0, 0));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kuisgame/speaker.png"))); // NOI18N
        jToggleButton1.setBorder(null);
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToggleButton1.setOpaque(true);
        jToggleButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/kuisgame/speaker-mute.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        panelCustomBar.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        getContentPane().add(panelCustomBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMulaiActionPerformed
        // ketika tombol di klik maka username akan disimpan ke database
        // apabila bila field kosong maka akan muncul pop up
        if (!inputNama.getText().equals("")) {
            String nama = inputNama.getText();
            setNama(nama);
            this.setVisible(false);
            new FrameMulaiKuis().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Masukkan Nama!",
                    "Error! Nama Kosong!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonMulaiActionPerformed

    private void buttonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCloseMouseClicked
        PlayMusic play = new PlayMusic();
        play.stopMusic();
        this.dispose();
    }//GEN-LAST:event_buttonCloseMouseClicked

    private void buttonMinimizedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMinimizedMouseClicked
        this.setState(FrameWelcome.ICONIFIED);
    }//GEN-LAST:event_buttonMinimizedMouseClicked

    private void panelBaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBaseMouseClicked
        
    }//GEN-LAST:event_panelBaseMouseClicked

    private void iconLoginAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconLoginAdminMouseClicked
        // pindah halaman ke login admin
        this.setVisible(false);
        LoginAdmin login = new LoginAdmin();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_iconLoginAdminMouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.isSelected()) {
            new PlayMusic().stopMusic();
        } else {
            new PlayMusic().playMusic();
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameWelcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonClose;
    private javax.swing.JLabel buttonMinimized;
    private javax.swing.JButton buttonMulai;
    private javax.swing.JLabel iconLoginAdmin;
    private javax.swing.JTextField inputNama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelTitleApp;
    private javax.swing.JLabel labelTopScore;
    private javax.swing.JPanel panelBase;
    private javax.swing.JPanel panelCustomBar;
    private javax.swing.JPanel panelLeftWelcome;
    private javax.swing.JPanel panelRightWelcome;
    private javax.swing.JPanel panelScore;
    private javax.swing.JTable tableScore;
    // End of variables declaration//GEN-END:variables

    private void LoadData() {
        try {
            s = conn.createStatement();
            String query = "SELECT * FROM user ORDER BY score DESC LIMIT 10";
            ResultSet r = s.executeQuery(query);
            int i = 1;
            while(r.next()){
                Object [] obj = new Object[3];
                obj[0] = i;
                obj[1] = r.getString("nama");
                obj[2] = r.getInt("score");
                i++;
                scoreModel.addRow(obj);
            }
        } catch (SQLException e) {
            System.out.println("Error: Tidak Bisa Mengambil Data Score!");
        }
    }
    
    
}